const DIFFICULTY_LEVELS = [
  {
    id: 1,
    name: '1',
    level: '1组',
    range: [0, 3],
    operation: 'add',
    stage: 'addTiny',
    questionCount: 10,
    description: '0-3 加法',
    helperText: '小数一起加一加',
    color: 'var(--candy-mint-light)',
    textColor: 'var(--candy-mint-dark)',
    stars: 1
  },
  {
    id: 2,
    name: '2',
    level: '1组',
    range: [0, 3],
    operation: 'subtract',
    stage: 'subtractTiny',
    questionCount: 10,
    description: '0-3 减法',
    helperText: '拿走几个看一看',
    color: 'var(--candy-mint)',
    textColor: 'var(--candy-mint-dark)',
    stars: 1
  },
  {
    id: 3,
    name: '3',
    level: '1组',
    range: [0, 3],
    operation: 'mixed',
    stage: 'mixedTiny',
    questionCount: 12,
    description: '0-3 加减',
    helperText: '加一加，也减一减',
    color: 'var(--candy-mint-dark)',
    textColor: 'var(--candy-mint-dark)',
    stars: 2
  },
  {
    id: 4,
    name: '4',
    level: '2组',
    range: [0, 5],
    operation: 'add',
    stage: 'addWithinFive',
    questionCount: 12,
    description: '5 以内加法',
    helperText: '把小数慢慢加到 5',
    color: 'var(--candy-pink-light)',
    textColor: 'var(--candy-pink-dark)',
    stars: 2
  },
  {
    id: 5,
    name: '5',
    level: '2组',
    range: [0, 5],
    operation: 'subtract',
    stage: 'subtractWithinFive',
    questionCount: 12,
    description: '5 以内减法',
    helperText: '从 5 里拿走几个',
    color: 'var(--candy-pink)',
    textColor: 'var(--candy-pink-dark)',
    stars: 2
  },
  {
    id: 6,
    name: '6',
    level: '2组',
    range: [0, 5],
    operation: 'mixed',
    stage: 'mixedWithinFive',
    questionCount: 15,
    description: '5 以内加减',
    helperText: '看看是变多还是变少',
    color: 'var(--candy-pink-dark)',
    textColor: 'var(--candy-pink-dark)',
    stars: 3
  },
  {
    id: 7,
    name: '7',
    level: '3组',
    range: [0, 5],
    operation: 'add',
    stage: 'pairsWithinFive',
    questionCount: 15,
    description: '5 以内组合',
    helperText: '记住好朋友数字',
    color: 'var(--candy-yellow-light)',
    textColor: 'var(--candy-yellow-dark)',
    stars: 3
  },
  {
    id: 8,
    name: '8',
    level: '3组',
    range: [0, 5],
    operation: 'missingAddMixed',
    stage: 'splitWithinFive',
    questionCount: 12,
    description: '把 5 分成两个数',
    helperText: '看看 5 能分成谁和谁',
    color: 'var(--candy-yellow)',
    textColor: 'var(--candy-yellow-dark)',
    stars: 3
  },
  {
    id: 9,
    name: '9',
    level: '3组',
    range: [0, 10],
    operation: 'add',
    stage: 'withinTenIntroAdd',
    questionCount: 14,
    description: '10 以内加法入门',
    helperText: '先从小步加法开始',
    color: 'var(--candy-yellow)',
    textColor: 'var(--candy-yellow-dark)',
    stars: 3
  },
  {
    id: 10,
    name: '10',
    level: '4组',
    range: [0, 10],
    operation: 'subtract',
    stage: 'withinTenIntroSubtract',
    questionCount: 14,
    description: '10 以内减法入门',
    helperText: '先做轻松的小步减法',
    color: 'var(--candy-yellow-dark)',
    textColor: 'var(--candy-yellow-dark)',
    stars: 3
  },
  {
    id: 11,
    name: '11',
    level: '4组',
    range: [0, 10],
    operation: 'add',
    stage: 'makeTen',
    questionCount: 15,
    description: '10 的组成',
    helperText: '看看谁和谁能凑成 10',
    color: 'var(--candy-peach-light)',
    textColor: 'var(--candy-peach-dark)',
    stars: 4
  },
  {
    id: 12,
    name: '12',
    level: '4组',
    range: [0, 10],
    operation: 'missingAddMixed',
    stage: 'splitWithinTen',
    questionCount: 14,
    description: '把 10 分成两个数',
    helperText: '把 10 拆成两个好朋友',
    color: 'var(--candy-peach)',
    textColor: 'var(--candy-peach-dark)',
    stars: 3
  },
  {
    id: 13,
    name: '13',
    level: '5组',
    range: [0, 10],
    operation: 'add',
    stage: 'withinTenAdd',
    questionCount: 15,
    description: '10 以内加法',
    helperText: '把 10 以内加法练熟',
    color: 'var(--candy-peach)',
    textColor: 'var(--candy-peach-dark)',
    stars: 4
  },
  {
    id: 14,
    name: '14',
    level: '5组',
    range: [0, 10],
    operation: 'subtract',
    stage: 'withinTenSubtract',
    questionCount: 16,
    description: '10 以内减法',
    helperText: '把 10 以内减法练熟',
    color: 'var(--candy-peach-dark)',
    textColor: 'var(--candy-peach-dark)',
    stars: 4
  },
  {
    id: 15,
    name: '15',
    level: '5组',
    range: [0, 20],
    operation: 'add',
    stage: 'teenAdd',
    questionCount: 16,
    description: '10几加几',
    helperText: '先从 10 开始往上加',
    color: 'var(--candy-lavender-light)',
    textColor: 'var(--candy-lavender-dark)',
    stars: 4
  },
  {
    id: 16,
    name: '16',
    level: '6组',
    range: [0, 20],
    operation: 'subtract',
    stage: 'teenSubtract',
    questionCount: 16,
    description: '10几减几',
    helperText: '从 10几里慢慢减掉',
    color: 'var(--candy-lavender)',
    textColor: 'var(--candy-lavender-dark)',
    stars: 4
  },
  {
    id: 17,
    name: '17',
    level: '6组',
    range: [0, 20],
    operation: 'add',
    stage: 'bridgeTenAdd',
    questionCount: 16,
    description: '20 以内过十加',
    helperText: '先凑到 10，再往上加',
    color: 'var(--candy-lavender-dark)',
    textColor: 'var(--candy-lavender-dark)',
    stars: 5
  },
  {
    id: 18,
    name: '18',
    level: '6组',
    range: [0, 20],
    operation: 'subtract',
    stage: 'bridgeTenSubtract',
    questionCount: 18,
    description: '20 以内退位减',
    helperText: '先退回 10，再减下去',
    color: 'var(--candy-mint-light)',
    textColor: 'var(--candy-mint-dark)',
    stars: 5
  },
  {
    id: 19,
    name: '19',
    level: '7组',
    range: [0, 20],
    operation: 'mixed',
    stage: 'withinTwentyMixed',
    questionCount: 18,
    description: '20 以内加减',
    helperText: '把前面学过的都用起来',
    color: 'var(--candy-yellow-light)',
    textColor: 'var(--candy-yellow-dark)',
    stars: 5
  },
  {
    id: 20,
    name: '20',
    level: '7组',
    range: [0, 12],
    operation: 'missingAddMixed',
    stage: 'missingNumberIntro',
    questionCount: 20,
    description: '找空格',
    helperText: '想想哪一个数躲起来了',
    color: 'var(--candy-peach-light)',
    textColor: 'var(--candy-peach-dark)',
    stars: 5
  }
]

export const DIFFICULTY_GROUPS = [
  { name: '1组', levels: [1, 2, 3], color: 'mint' },
  { name: '2组', levels: [4, 5, 6], color: 'pink' },
  { name: '3组', levels: [7, 8, 9], color: 'yellow' },
  { name: '4组', levels: [10, 11, 12], color: 'peach' },
  { name: '5组', levels: [13, 14, 15], color: 'lavender' },
  { name: '6组', levels: [16, 17, 18], color: 'mint' },
  { name: '7组', levels: [19, 20], color: 'yellow' }
]

export const TOTAL_LEVELS = DIFFICULTY_LEVELS.length

export function getDifficultyById(id) {
  return DIFFICULTY_LEVELS.find(d => d.id === parseInt(id, 10))
}
