const DIFFICULTY_LEVELS = [
  {
    id: 1,
    name: '1',
    level: '1组',
    range: [0, 3],
    operation: 'add',
    stage: 'addTiny',
    questionCount: 20,
    description: '0-3 加法',
    helperText: '把两个小数字加起来',
    color: 'var(--candy-mint-light)',
    textColor: 'var(--candy-mint-dark)',
    stars: 1
  },
  {
    id: 2,
    name: '2',
    level: '1组',
    range: [0, 3],
    operation: 'subtract',
    stage: 'subtractTiny',
    questionCount: 20,
    description: '0-3 减法',
    helperText: '拿走几个看一看',
    color: 'var(--candy-mint)',
    textColor: 'var(--candy-mint-dark)',
    stars: 1
  },
  {
    id: 3,
    name: '3',
    level: '1组',
    range: [0, 3],
    operation: 'mixed',
    stage: 'mixedTiny',
    questionCount: 24,
    description: '0-3 加减',
    helperText: '加一加，也减一减',
    color: 'var(--candy-mint-dark)',
    textColor: 'var(--candy-mint-dark)',
    stars: 2
  },
  {
    id: 4,
    name: '4',
    level: '2组',
    range: [0, 5],
    operation: 'add',
    stage: 'addWithinFive',
    questionCount: 24,
    description: '5 以内加法',
    helperText: '把 5 以内的数加起来',
    color: 'var(--candy-blue-light)',
    textColor: 'var(--candy-blue-dark)',
    stars: 2
  },
  {
    id: 5,
    name: '5',
    level: '2组',
    range: [0, 5],
    operation: 'subtract',
    stage: 'subtractWithinFive',
    questionCount: 24,
    description: '5 以内减法',
    helperText: '从 5 以内的数里拿走几个',
    color: 'var(--candy-blue)',
    textColor: 'var(--candy-blue-dark)',
    stars: 2
  },
  {
    id: 6,
    name: '6',
    level: '2组',
    range: [0, 5],
    operation: 'mixed',
    stage: 'mixedWithinFive',
    questionCount: 30,
    description: '5 以内加减',
    helperText: '看看是变多还是变少',
    color: 'var(--candy-blue-dark)',
    textColor: 'var(--candy-blue-dark)',
    stars: 3
  },
  {
    id: 7,
    name: '7',
    level: '3组',
    range: [0, 5],
    operation: 'add',
    stage: 'pairsWithinFive',
    questionCount: 30,
    description: '5 以内组合',
    helperText: '找找哪些数字能合在一起',
    color: 'var(--candy-yellow-light)',
    textColor: 'var(--candy-yellow-dark)',
    stars: 3
  },
  {
    id: 8,
    name: '8',
    level: '3组',
    range: [0, 5],
    operation: 'missingAddMixed',
    stage: 'gapWithinFive',
    questionCount: 24,
    description: '5 以内找缺数',
    helperText: '找出藏起来的数',
    color: 'var(--candy-yellow)',
    textColor: 'var(--candy-yellow-dark)',
    stars: 3
  },
  {
    id: 9,
    name: '9',
    level: '3组',
    range: [0, 5],
    operation: 'missingAddMixed',
    stage: 'splitWithinFive',
    questionCount: 24,
    description: '5 以内拆分',
    helperText: '把一个数分成两个数',
    color: 'var(--candy-yellow)',
    textColor: 'var(--candy-yellow-dark)',
    stars: 3
  },
  {
    id: 10,
    name: '10',
    level: '4组',
    range: [0, 10],
    operation: 'add',
    stage: 'withinTenIntroAdd',
    questionCount: 28,
    description: '10 以内加法入门',
    helperText: '先从小步加法开始',
    color: 'var(--candy-yellow)',
    textColor: 'var(--candy-yellow-dark)',
    stars: 3
  },
  {
    id: 11,
    name: '11',
    level: '4组',
    range: [0, 10],
    operation: 'subtract',
    stage: 'withinTenIntroSubtract',
    questionCount: 28,
    description: '10 以内减法入门',
    helperText: '先做轻松的小步减法',
    color: 'var(--candy-yellow-dark)',
    textColor: 'var(--candy-yellow-dark)',
    stars: 3
  },
  {
    id: 12,
    name: '12',
    level: '4组',
    range: [0, 10],
    operation: 'add',
    stage: 'makeTen',
    questionCount: 30,
    description: '10 的组成',
    helperText: '看看谁和谁能凑成 10',
    color: 'var(--candy-peach-light)',
    textColor: 'var(--candy-peach-dark)',
    stars: 4
  },
  {
    id: 13,
    name: '13',
    level: '5组',
    range: [0, 10],
    operation: 'missingAddMixed',
    stage: 'gapWithinTen',
    questionCount: 28,
    description: '10 以内找缺数',
    helperText: '想想还差几到目标数',
    color: 'var(--candy-peach)',
    textColor: 'var(--candy-peach-dark)',
    stars: 3
  },
  {
    id: 14,
    name: '14',
    level: '5组',
    range: [0, 10],
    operation: 'missingAddMixed',
    stage: 'splitWithinTen',
    questionCount: 28,
    description: '10 以内拆分',
    helperText: '把 10 以内的数拆开',
    color: 'var(--candy-peach)',
    textColor: 'var(--candy-peach-dark)',
    stars: 3
  },
  {
    id: 15,
    name: '15',
    level: '5组',
    range: [0, 10],
    operation: 'add',
    stage: 'withinTenAdd',
    questionCount: 30,
    description: '10 以内加法',
    helperText: '把 10 以内加法练熟',
    color: 'var(--candy-peach)',
    textColor: 'var(--candy-peach-dark)',
    stars: 4
  },
  {
    id: 16,
    name: '16',
    level: '6组',
    range: [0, 10],
    operation: 'subtract',
    stage: 'withinTenSubtract',
    questionCount: 32,
    description: '10 以内减法',
    helperText: '把 10 以内减法练熟',
    color: 'var(--candy-peach-dark)',
    textColor: 'var(--candy-peach-dark)',
    stars: 4
  },
  {
    id: 17,
    name: '17',
    level: '6组',
    range: [0, 10],
    operation: 'mixed',
    stage: 'withinTenMixed',
    questionCount: 32,
    description: '10 以内综合',
    helperText: '把前面学过的方法一起用起来',
    color: 'var(--candy-lavender-light)',
    textColor: 'var(--candy-lavender-dark)',
    stars: 4
  },
  {
    id: 18,
    name: '18',
    level: '7组',
    range: [0, 20],
    operation: 'add',
    stage: 'teenAdd',
    questionCount: 32,
    description: '十几加几',
    helperText: '从十几开始往上加',
    color: 'var(--candy-lavender-light)',
    textColor: 'var(--candy-lavender-dark)',
    stars: 4
  },
  {
    id: 19,
    name: '19',
    level: '7组',
    range: [0, 20],
    operation: 'subtract',
    stage: 'teenSubtract',
    questionCount: 32,
    description: '十几减几',
    helperText: '从十几里减去几个',
    color: 'var(--candy-lavender)',
    textColor: 'var(--candy-lavender-dark)',
    stars: 4
  },
  {
    id: 20,
    name: '20',
    level: '7组',
    range: [0, 10],
    operation: 'add',
    stage: 'makeTenBridge',
    questionCount: 32,
    description: '凑到 10',
    helperText: '先把 10 凑稳',
    color: 'var(--candy-lavender-dark)',
    textColor: 'var(--candy-lavender-dark)',
    stars: 4
  },
  {
    id: 21,
    name: '21',
    level: '8组',
    range: [0, 20],
    operation: 'add',
    stage: 'bridgeTenAdd',
    questionCount: 32,
    description: '20 以内凑十加法',
    helperText: '先凑到 10，再往上加',
    color: 'var(--candy-lavender-dark)',
    textColor: 'var(--candy-lavender-dark)',
    stars: 5
  },
  {
    id: 22,
    name: '22',
    level: '8组',
    range: [0, 20],
    operation: 'subtract',
    stage: 'subtractFromTen',
    questionCount: 32,
    description: '从 10 往下减',
    helperText: '先练 10 附近减法',
    color: 'var(--candy-mint-light)',
    textColor: 'var(--candy-mint-dark)',
    stars: 4
  },
  {
    id: 23,
    name: '23',
    level: '8组',
    range: [0, 20],
    operation: 'subtract',
    stage: 'bridgeTenSubtract',
    questionCount: 36,
    description: '20 以内破十减法',
    helperText: '先减到 10，再继续减',
    color: 'var(--candy-mint-light)',
    textColor: 'var(--candy-mint-dark)',
    stars: 5
  },
  {
    id: 24,
    name: '24',
    level: '9组',
    range: [0, 20],
    operation: 'mixed',
    stage: 'withinTwentyMixed',
    questionCount: 36,
    description: '20 以内加减',
    helperText: '把前面学过的都用起来',
    color: 'var(--candy-yellow-light)',
    textColor: 'var(--candy-yellow-dark)',
    stars: 5
  },
  {
    id: 25,
    name: '25',
    level: '9组',
    range: [0, 12],
    operation: 'missingAddMixed',
    stage: 'missingNumberIntro',
    questionCount: 40,
    description: '找缺数',
    helperText: '找出藏起来的数',
    color: 'var(--candy-peach-light)',
    textColor: 'var(--candy-peach-dark)',
    stars: 5
  },
  {
    id: 26,
    name: '26',
    level: '9组',
    range: [0, 20],
    operation: 'mixed',
    stage: 'withinTwentyMixedAdvanced',
    questionCount: 40,
    description: '20 以内综合进阶',
    helperText: '把加减、找缺数和凑十一起用起来',
    color: 'var(--candy-peach-light)',
    textColor: 'var(--candy-peach-dark)',
    stars: 5
  }
]

export const DIFFICULTY_GROUPS = [
  { name: '1组', levels: [1, 2, 3], color: 'mint' },
  { name: '2组', levels: [4, 5, 6], color: 'pink' },
  { name: '3组', levels: [7, 8, 9], color: 'yellow' },
  { name: '4组', levels: [10, 11, 12], color: 'peach' },
  { name: '5组', levels: [13, 14, 15], color: 'peach' },
  { name: '6组', levels: [16, 17], color: 'lavender' },
  { name: '7组', levels: [18, 19, 20], color: 'lavender' },
  { name: '8组', levels: [21, 22, 23], color: 'mint' },
  { name: '9组', levels: [24, 25, 26], color: 'yellow' }
]

export const TOTAL_LEVELS = DIFFICULTY_LEVELS.length

export function getDifficultyById(id) {
  return DIFFICULTY_LEVELS.find(d => d.id === parseInt(id, 10))
}
